### ISSUE TITLE
🐛  Windows Inline Sysprep customization: Timezone with leading zeros

### ISSUE THREAD

**Issue by srm09** [vmware-tanzu/vm-operator#314]
**What steps did you take and what happened?**
To customize the Timezone when bootstrapping using inline sysprep, any time zone with leading zeros `020` gets converted to `16` when being passed to the `CustomizationSysprep`. This leads to the time zone being set incorrectly and thus blocking the VM to power due to customization failure.  

**What did you expect to happen?**
When a time zone with leading zeroes is submitted, the customization should pass and the VM should be powered on.

**Is there anything else you would like to add?**
```yaml
---
apiVersion: vmoperator.vmware.com/v1alpha2
kind: VirtualMachine
metadata:
  name:      win-inline-sysprep
  namespace: trial
spec:
  className:    best-effort-small
  imageName:    vmi-d855a48c1095cf2d9
  storageClass: wcpglobal-storage-profile
  powerState: PoweredOn
  bootstrap:
    sysprep:
      sysprep:
        guiRunOnce:
          commands: 
          - 'C:\sysprep\guestcustutil.exe restoreMountedDevices'
          - 'C:\sysprep\guestcustutil.exe flagComplete'
          - 'C:\sysprep\guestcustutil.exe deleteContainingFolder'
        guiUnattended: 
          autoLogon: true
          autoLogonCount: 1
          timeZone: 020
          password:
            name: win-inline-sysprep-secret
        identification:
          domainAdmin: blah
          domainAdminPassword:
            name: win-inline-sysprep-secret
          joinDomain: foo
        licenseFilePrintData:
          autoMode: perServer
          autoUsers: 5
        userData:
          fullName: "First User"
          orgName: "Broadcom"
---
apiVersion: v1
kind: Secret
metadata:
  name: win-inline-sysprep-secret
  namespace: trial
stringData:
  "password": "Ponies!23"
  "domain_admin_password": "Ponies!23"

```

**Please tell us about your environment.**

<table>
<tr>
<td></td>
<th>Value</th>
<th>How to Obtain</th>
</tr>
<tr>
<th>Supervisor version</th>
<td><code></code></td>
<td><code>rpm -qa VMware-wcp</code> on the vCenter appliance</td>
</tr>
<tr>
<th>Supervisor node image version</th>
<td><code></code></td>
<td><code>rpm -qa VMware-wcpovf</code> on the vCenter appliance</td>
</tr>
<tr>
<th>Kubernetes version</th>
<td><code></code></td>
<td><code>kubectl version</code></td>
</tr>
<tr>
<th>VM Operator version</th>
<td><code></code></td>
<td>

```shell
kubectl -n vmware-system-vmop get pods \
  -ojsonpath='{range .items[*].spec.containers[*]}{.image}{"\n"}{end}' | \
  sort -u | \
  grep vmop | \
  awk -F'/' '{print $3}' | \
  awk -F: '{print $2}'
```

</td>
</tr>
</table>
