### ISSUE TITLE
v1a1 VM with cloud-init bootstrap containing only SSH public keys cannot be deployed in v1a2/v1a3 enabled cluster

### ISSUE THREAD

**Issue by dilyar85** [vmware-tanzu/vm-operator#585]
**What steps did you take and what happened?**

Deploy a v1a1 VM to a Supervisor cluster where the v1a2 or v1a3 version is enabled, with cloud-init bootstrap containing only the `ssh-public-keys` config in Secret data, e.g.:
```yaml
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vm-only-pubkey
  namespace: 111-ns
  labels:
    vm-selector: vm-only-pubkey
spec:
  className: best-effort-xsmall
  imageName: vmi-9287a6a002dd60237
  storageClass: wcpglobal-storage-profile
  powerState: poweredOn
  vmMetadata:
    secretName: vm-only-pubkey-bootstrap-secret
    transport: CloudInit
---
apiVersion: v1
kind: Secret
metadata:
  name: vm-only-pubkey-bootstrap-secret
  namespace: 111-ns
  labels:
    vm-selector: vm-only-pubkey
stringData:
  ssh-public-keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDjgtQzx+88iqD5n79isDtQ1l7yS9Gw06ZJM54+qWY30KM9LQY9bKXW2tMId0p8DXSWP+zs6j9Xn6VHnGyVf5i0xMCNOiqp/jMgysYwWPPHs+02ERECBjO4liUwE1FK9PM4nCd7O1zBBtb8ddDQPUd+cv6YiU/oTEvgd4NKLaNOr39ip+xQDIPiW9ZNlWRr5HCLGMMBYSm9xvDIvDVBOtetckhQMLGOmSySbaSR1QPRB5VItjern9Xkv6epxBWWO9/m11K8zefLP9R5AttOFdiukQXaKrp+Gs9hp+epH5Cr3cGAAONDVCiETblbhOKdh0n4tZ83R2ItauKmRrQBb9KBo1gRqOcqIwSQS55tS2lKFSXNikb0Q0+q8f199hVgPV7rjafOCAU/FkHSWk50cv881gLy3Zxm/yqix3/uLqp34fWyRc5pZi66gOALCOBnglNWeBD7Ab01IaxdIqIgT9JNZrEM4u6QBPmnSAHHsJCy9lM2Y7tcqFRJcx6lCqJS7+dTJzE1CddqMQ/7PmaZ7TQi7mN/yjgDw7O8oWMkjXNzg2HHbAhrBJyxzswLvYRexzgq56RSWAKjXSqEKK5CQTGfen4NgrNsRk3MKisMZBd4VEmPnuEmLODw//atfq5EBnW3a63mwgaHamhioyNtJ6uk/w308vz7JRpgkX9GLxH00w== somashekars@somashekars-a01.vmware.com
```

The VM can be converted to v1a2 or v1a3, but deployment failed with a `required key "user-data" not found in Secret <secret-name>` error reported.

**What did you expect to happen?**

The VM should be deployed successfully with the SSH public keys added to the VM.

**Is there anything else you would like to add?**

A possible fix could be adding `ssh-public-keys` as another well-known cloud-init key (separate from the existing `CloudInitUserDataSecretKeys`, and check it only if the latter are not found) here: https://github.com/vmware-tanzu/vm-operator/blob/main/pkg/providers/vsphere/vmprovider_vm_utils.go#L306-L311

**Please tell us about your environment.**

N/A
